version: '2'
services:
  app:
    container_name: go-api
    build: .
    ports: 
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mysql 

  mysql:
    container_name: db_mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin 
      MYSQL_PASSWORD: password 
      MYSQL_DATABASE: example 

